// <auto-generated />
using EntityFrameworkExamples;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkExamples.Migrations
{
    [DbContext(typeof(FruitsDbContext))]
    [Migration("20201218142328_BasketMakers")]
    partial class BasketMakers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BasketMakerFruitBasket", b =>
                {
                    b.Property<int>("BasketMakersID")
                        .HasColumnType("int");

                    b.Property<int>("FruitBasketsID")
                        .HasColumnType("int");

                    b.HasKey("BasketMakersID", "FruitBasketsID");

                    b.HasIndex("FruitBasketsID");

                    b.ToTable("BasketMakerFruitBasket");
                });

            modelBuilder.Entity("EntityFrameworkExamples.Models.BasketMaker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("ID");

                    b.ToTable("BasketMakers");
                });

            modelBuilder.Entity("EntityFrameworkExamples.Models.FruitBasket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Banana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FruitBaskets");
                });

            modelBuilder.Entity("BasketMakerFruitBasket", b =>
                {
                    b.HasOne("EntityFrameworkExamples.Models.BasketMaker", null)
                        .WithMany()
                        .HasForeignKey("BasketMakersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameworkExamples.Models.FruitBasket", null)
                        .WithMany()
                        .HasForeignKey("FruitBasketsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
